USE BankingDB ;
SELECT SUM(Balance) AS Total_Balance
FROM Accounts
WHERE AccountType = 'Savings';

SELECT AVG(Balance) AS AVERAGE_BALANCE 
FROM Accounts ;

SELECT MAX(Balance) as Highest_Balance from Accounts ;

SELECT MIN(Balance) as Lowest_Balance from Accounts ;

SELECT COUNT(CustomerID) as Total_Customer from Customers ; 

SELECT COUNT(*) AS total_accounts
FROM Accounts; 

SELECT ACCOUNTTYPE,SUM(BALANCE) AS TOTAL_BALANCE FROM ACCOUNTS GROUP BY Accounttype ;

SELECT ACCOUNTTYPE,MAX(BALANCE) AS TOTAL_BALANCE FROM ACCOUNTS GROUP BY ACCOUNTTYPE ;



SELECT 
    ACCOUNTTYPE, SUM(BALANCE) AS TOATL_BALANCE
FROM
    ACCOUNTS
GROUP BY ACCOUNTTYPE
HAVING SUM(BALANCE) > 25000 ;



SELECT 
    ACCOUNTTYPE, SUM(BALANCE) AS TOATL_BALANCE
FROM
    ACCOUNTS
GROUP BY ACCOUNTTYPE
having SUM(BALANCE) > 120000 ;


